### ISSUE TITLE
Setting the video size to record in

### ISSUE THREAD

**Issue by pcm2a** [pvasa/cameraview-ex#105]
Before I start adding this in I wanted to make sure it is not already available and I have missed it.

Current functionality:
The user can get the list of valid aspect ratios and set one, example 16:9.
When the recording starts a video size is automatically chosen by the closest size to the screen preview and the selected aspect ratio.

Example: On a LG G6 set at 16:9 using a full screen preview this results in a 2560x1440 video.

Enhancement:
- The ability to get the available video sizes for the current camera
- The ability to specify a video size to record in

Example: On a LG G6 set at 16:9 be able to record in 1900x1080 or 1280x720

**Comment by pvasa** [comment]
Fixed in #108
