### ISSUE TITLE
Camera1 Video Recording Support Or Throw Not Supported Exception

### ISSUE THREAD

**Issue by keremkusmezer** [pvasa/cameraview-ex#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keremkusmezer** [comment]
When the api falls back to Camera1 during VideoRecording, the startVideoRecording method is empty as well as the stop resume pause methods are returning false directly, do you have any plans to implement video recording for the Camera1 implementation and can't you just throw a NotSupported exception on startVideoRecording or execute the callback directly instead of leaving it empty?

**Comment by pvasa** [comment]
There is no plan to include video support for camera1 any time soon. I will add an error for those methods.

**Comment by pvasa** [comment]
Video capture is now supported.
