### ISSUE TITLE
How to get the cameraMode in 3.0.1 beta?

### ISSUE THREAD

**Issue by pcm2a** [pvasa/cameraview-ex#142]
In the latest 3.0.1 beta it looks like `camera.cameraMode` has been replaced with `camera.setCameraMode(int)`. Is there some other mechanism to get the current camera mode or is it now up to the client to keep a reference to which mode the camera is in?

Maybe I could add a getter into `CameraView.kt`
```
fun getCameraMode() : Int {
   return config.cameraMode.value
}
```

**Comment by pvasa** [comment]
@pcm2a There is a way, there are now 3 booleans, `isSingleCaptureModeEnabled`, `isVideoCaptureModeEnabled`, and `isSingleCaptureModeEnabled` to check for each more if it is enabled.
