### ISSUE TITLE
Front facing camera doesn't fire addPictureTakenListener event

### ISSUE THREAD

**Issue by WilliamAlexander** [pvasa/cameraview-ex#174]
**Describe the bug**
Front facing camera doesn't fire addPictureTakenListener event

**To Reproduce**
1. Set camera to front facing
2. Call camera.capture()
3. The addPictureTakenListener does not fire
4. When camera is set to Back, it works fine and I'm able to save the image

**Expected behavior**
Save Image from addPictureTakenListener

**Using ProGuard**
- [ ] with ProGuard

**Screenshots**
n/a

**Device: Not OK**
 - Device: [Google Pixel 2]
 - OS: [Android Pie (9.0)]
 - Nexus 5x device [ Android Oreo]

**Device OK:**
 - Device: [Samsung Tab 2] Android 7.0

**Branch Name (if using as a local module)**
- [ ] master

**Comment by pvasa** [comment]
@WilliamAlexander Have you tried setting an error listener? If not please set `CameraView.addCameraErrorListener { throwable, level -> .. }` and see if it throws any error when you try to take picture from front camera. If there is some error it might give some insight about the issue.

**Comment by WilliamAlexander** [comment]
@pvasa Thanks for the reply.
I have an error listener. 
I only get a warning:
"AF is not possible. Turning it off"

**Comment by pvasa** [comment]
@WilliamAlexander the warning you're seeing only means auto focus is not supported and turned off. That shouldn't hinder other functionalities like taking pictures. Are you seeing same behavior while using sample app on the same device? Also please make sure that single capture mode is enabled; you can do that by checking `cameraView.isSingleCaptureModeEnabled`.
