### ISSUE TITLE
Was sampleApp moved to CameraEx/sampleApp?

### ISSUE THREAD

**Issue by pcm2a** [pvasa/cameraview-ex#175]
I'm working on merging the latest dev branch into my fork and to also integrate it in with my fork's changes. I've encountered a question that I think you can clear up. Was the root sampleApp project refactored into CameraEx/sampleApp?

I can't figure out how to get it to build the CameraEx/sampleApp in Android Studio 3.3.2. cameraViewEx and sampleAppJava show up as projects.

I tried adding it into settings.gradle.kts:
```
include(":cameraViewEx", ":sampleAppJava")
include(":CameraEx")
```

https://imgur.com/a/gOn8to4

Update I tried with this and then it shows up as a module that can be built, but fails to build.
`include(":CameraEx:sampleApp")`

```
ERROR: Failed to resolve: com.priyankvasa.android:cameraview-ex:3.4.3-debug
Show in Project Structure dialog
Affected Modules: sampleApp
```

Probably this should reference the local project instead of a remote dependency?
`implementation("com.priyankvasa.android:cameraview-ex:3.4.3-debug")`

**Comment by pvasa** [comment]
@pcm2a Yes I moved `sampleApp` to a separate project `CameraEx`. Open CameraEx as project and it should load correctly with only one module. The reason behind doing this is to test library inside an AndroidX project. 

Open CameraEx project and run following gradle commands
- build and deploy lib module - `cleanCameraViewEx buildCameraViewEx`
- build sampleApp - `clean assemble`
