### ISSUE TITLE
Auto focus listener

### ISSUE THREAD

**Issue by xperiafan13-rom** [pvasa/cameraview-ex#185]
Hi, how i cad add listener for automatic focus without set points on startAutofocus?

**Comment by pvasa** [comment]
Hi @xperiafan13-rom can you please elaborate the question? What kind of events are you trying to listen to?

**Comment by xperiafan13-rom** [comment]
Soory, What I want is to implement a listener for an autofocus without needing some genre or using the startAutofocus function, that is, when doing automatic aoutocus to capture the image

**Comment by pvasa** [comment]
@xperiafan13-rom I still don't get what you are looking but if you mean using automatic focus, you can set [`app:autoFocus="continuous_picture"`](https://github.com/pvasa/cameraview-ex#in-layout-xml) when defining camera view in your layout file. Or you can also set it programmatically by calling `cameraView.autoFocus = Modes.AutoFocus.AF_CONTINUOUS_PICTURE`.
