### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [pvasa/cameraview-ex#198]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by pvasa** [comment]
Hi @mansya, good day. I am okay with it. What kind of logo do you have in mind?

**Comment by mansya** [comment]
hi sir. I have completed the design for this project. How ? do you like it ? if yes which one do you like?
![cameraview-ex](https://user-images.githubusercontent.com/33461607/61067286-5cdf4680-a431-11e9-8700-210252968864.png)

**Comment by pvasa** [comment]
Hi @mansya thanks for putting them together. I liked the 3rd.

**Comment by mansya** [comment]
hi sir. I have sent you [**Pull Requests**](https://github.com/pvasa/cameraview-ex/pull/200). please check. and I have also uploaded all files to this [**Drive**](https://drive.google.com/open?id=1tcwD5q3cKuzZn8qii6Hnesqut9blqkRU)

**Comment by mansya** [comment]
Sir. How about the pull requests that I sent?

**Comment by mansya** [comment]
I don't understand that. can you explain it?
