### ISSUE TITLE
Library automatically adds RECORD_AUDIO

### ISSUE THREAD

**Issue by florianhirson** [pvasa/cameraview-ex#199]
**Describe the bug**
I use the library only to take pictures and the permission RECORD_AUDIO is automatically added to the manifest. 

Is there a way to avoid this permission to be added ?

**Comment by pvasa** [comment]
@florianhirson audio permission in Android requires explicit approval from user. So even if it is added in manifest, it won't be approved by default. You need to ask explicitly for runtime permission.

**Comment by rocca23** [comment]
I think it's not the better approach to add all potentially used permission in the library manifest. Apps end up declaring permissions that they don't use and this may be relevant with Android < 6, where users accept permissions upfront. I think you should document what permissions are needed to use the relevant features and leave to developers the declaration of such permissions in their manifest.

For anyone looking into this issue, in the meanwhile you can remove unwanted permission (like the suspicious record audio permission) in this way:
```xml
<uses-permission
        android:name="android.permission.RECORD_AUDIO"
        tools:node="remove" />
```
