### ISSUE TITLE
Stretched preview after camera switch within an activity with android:screenOrientation="portrait"

### ISSUE THREAD

**Issue by J3y-S** [pvasa/cameraview-ex#201]
**Describe the bug**
Hello. I'm using your very nice to use Camera API in an activity with android:screenOrientation="portrait".
When i start in portrait orientation and switch the camera after I've rotated the device to landscape orientation the preview ist totally stretched and wrong rotated.

**To Reproduce**
1. Start Activity with android:screenOrientation="portrait" including CameraView (hold the device in portrait orientation)
2. Rotate device to landscape
3. Switch Camera

**Expected behavior**
A non streched camera preview aber switching the camera

**Using ProGuard**
- [ ] with ProGuard
- [X] without ProGuard

**Screenshots**
*Device in portrait mode works very good!*
![Screenshot_20190813-123147](https://user-images.githubusercontent.com/5833460/62935144-9dcad200-bdc6-11e9-86bc-9632a7037b02.jpg)

*Device rotated to landscape and camera switch twice (to front and again to back camera)*
![Screenshot_20190813-123233](https://user-images.githubusercontent.com/5833460/62935145-9dcad200-bdc6-11e9-9844-0610c1a1629c.jpg)

I'm using the Version 3.4.3

**Comment by pvasa** [comment]
Hi @J3y-S, I would suggest updating to `v3.5.4-alpha` and check if you still see this issue. A lot of preview and capture sizes related issues were fixed in some recent releases. If not then we can investigate more.

**Comment by pvasa** [comment]
You can find complete changelog [here](https://github.com/pvasa/cameraview-ex/releases).
