### ISSUE TITLE
jetified-cameraview-ex-3.5.5-alpha\res\values\values.xml: AAPT: error: expected enum but got (raw string) single_capture.

### ISSUE THREAD

**Issue by pedromarthon** [pvasa/cameraview-ex#210]
I am getting this error when compiling now

jetified-cameraview-ex-3.5.5-alpha\res\values\values.xml: AAPT: error: expected enum but got (raw string) single_capture.

**Comment by pedromarthon** [comment]
clean build worked, but now it freezes when I use flash

**Comment by ShankyPatel** [comment]
i am still getting same issue even after getting project cleaned.
